
package com.softlink.minilib.server.mailapi;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SendMailServiceImplService", targetNamespace = "http://sendmailservice.itpro.com/", wsdlLocation = "//WEB-INF/wsdl/SendMailService.wsdl")
public class SendMailServiceImplService
    extends Service
{

    private final static URL SENDMAILSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.softlink.minilib.server.mailapi.SendMailServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.softlink.minilib.server.mailapi.SendMailServiceImplService.class.getResource("//WEB-INF");
            url = new URL(baseUrl, "//WEB-INF/wsdl/SendMailService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'SendMailService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SENDMAILSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public SendMailServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendMailServiceImplService() {
        super(SENDMAILSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://sendmailservice.itpro.com/", "SendMailServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns SendMailService
     */
    @WebEndpoint(name = "SendMailServiceImplPort")
    public SendMailService getSendMailServiceImplPort() {
        return super.getPort(new QName("http://sendmailservice.itpro.com/", "SendMailServiceImplPort"), SendMailService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendMailService
     */
    @WebEndpoint(name = "SendMailServiceImplPort")
    public SendMailService getSendMailServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sendmailservice.itpro.com/", "SendMailServiceImplPort"), SendMailService.class, features);
    }

}
